name: lerobot
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - ffmpeg=7.1.1
  - cmake
  - pip:
    - git+https://github.com/huggingface/lerobot.git#egg=lerobot
    - wandb