name: lerobot
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - cmake
  - wandb==0.20.1
  - ffmpeg==7.1.1
  - pandas==2.2.2
  - jupyter==1.1.1
  - plotly==5.19.0
  - nbformat==5.10.4
  - ipykernel==6.29.5
  - ipywidgets==8.1.5
  - matplotlib==3.10.0
  - pip:
    - git+https://github.com/huggingface/lerobot.git#egg=lerobot